### ISSUE TITLE
Error when including package...

### ISSUE THREAD

**Issue by joetidee** [webpack/webpack-dev-middleware#163] opened 2016-12-20 17:23 UTC
Currently using latest version of webpack and webpack-dev-middleware. Here is my server/index.js file:

```
const express = require('express');
const bodyParser = require('body-parser');
const passport = require('passport');
var webpack = require('webpack');
var webpackConfig = require('./webpack.config.js');
var compiler = webpack(webpackConfig);
//var webpackMiddleware = require("webpack-dev-middleware");
```

When I uncomment the 'webpackMiddleware' line and run `sudo npm start` in the console, it throws this error:

```
> auth_app@1.0.0 start /tidee/auth_app
> nodemon --use_strict index.js

[nodemon] 1.11.0
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node --use_strict index.js`
/tidee/auth_app/node_modules/errno/custom.js:18
    Error.captureStackTrace(this, arguments.callee)
                                           ^

TypeError: 'caller', 'callee', and 'arguments' properties may not be accessed on strict mode functions or the arguments objects for calls to them
    at CustomError (/tidee/auth_app/node_modules/errno/custom.js:18:44)
    at createError (/tidee/auth_app/node_modules/errno/custom.js:42:43)
    at ce (/tidee/auth_app/node_modules/errno/custom.js:48:12)
    at module.exports (/tidee/auth_app/node_modules/errno/custom.js:52:25)
    at Object.<anonymous> (/tidee/auth_app/node_modules/errno/errno.js:312:44)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
```

**Comment by SpaceK33z** [comment] 2016-12-20 17:29
Can you provide a repo which reproduces this? This doesn't happen in my install. Also please provide your OS and Node.js version.

**Comment by SpaceK33z** [comment] 2016-12-20 17:30
Note that the `errno` module is used by `memory-fs` (which is a dep of `webpack-dev-middleware`), so it might be a bug there.

**Comment by joetidee** [comment] 2016-12-20 17:36
Wondering if it has somethign to do with `--use_strict` . This is the scripts snippet from my package.json file:

```
"scripts": {
    "start": "nodemon --use_strict index.js",
    "bundle": "webpack"
  },
```

when I changed it to :
```

"scripts": {
    "start": "nodemon index.js",
    "bundle": "webpack"
  },

```
the error goes away.

**Comment by SpaceK33z** [comment] 2016-12-20 17:39
Ah, yes it seems to be: https://github.com/rvagg/node-errno/issues/17

**Comment by SpaceK33z** [comment] 2016-12-20 17:42
Closing this since we can't do anything about that. If you really want to use strict mode, you can try to get https://github.com/rvagg/node-errno/pull/18 merged, or try to find a comparable module to `errno` and open up a PR on [memory-fs](https://github.com/webpack/memory-fs) that fixes it.

**Closed by SpaceK33z** 2016-12-20 17:42 UTC
