### ISSUE TITLE
Error: invalid arguments

### ISSUE THREAD

**Issue by lqzerogg** [webpack/webpack-dev-middleware#97] opened 2016-05-24 09:23 UTC
When I use this middleware, the server throw an Error.
I have searched answer for a long time, but I can't find any.
It's not because of the output.path in the config file.I have checked twice.

Here's my error stack:

```
webpack-dev-middleware/middleware.js:106
			if(err) throw err;
			        ^
Error: invalid argument
    at pathToArray (/Users/Zero/projects/webpack_react2/project_source/03_webpack_and_react/kanban_app/node_modules/memory-fs/lib/MemoryFileSystem.js:44:10)
    at MemoryFileSystem.mkdirpSync (/Users/Zero/projects/webpack_react2/project_source/03_webpack_and_react/kanban_app/node_modules/memory-fs/lib/MemoryFileSystem.js:139:13)
    at MemoryFileSystem.(anonymous function) [as mkdirp] (/Users/Zero/projects/webpack_react2/project_source/03_webpack_and_react/kanban_app/node_modules/memory-fs/lib/MemoryFileSystem.js:279:34)
    at Compiler.<anonymous> (/Users/Zero/projects/webpack_react2/project_source/03_webpack_and_react/kanban_app/node_modules/webpack/lib/Compiler.js:229:25)
    at Compiler.applyPluginsAsync (/Users/Zero/projects/webpack_react2/project_source/03_webpack_and_react/kanban_app/node_modules/tapable/lib/Tapable.js:60:69)
    at Compiler.emitAssets (/Users/Zero/projects/webpack_react2/project_source/03_webpack_and_react/kanban_app/node_modules/webpack/lib/Compiler.js:2
```

**Comment by lqzerogg** [comment] 2016-05-24 09:24
Here's my middleware option:
    // display no info to console (only warnings and errors)
    noInfo: false,

    // display nothing to the console
    quiet: false,

    // switch into lazy mode
    // that means no watching, but recompilation on every request
    lazy: false,

    // watch options (only lazy: false)
    watchOptions: {
        aggregateTimeout: 500,
        poll: true
    },

    // public path to bind the middleware to
    // use the same as in webpack
    publicPath: '/build/',

    // custom headers
    headers: { "X-Custom-Header": "yes" },

    // options for formating the statistics
    stats: {
        colors: true
    }

**Comment by lqzerogg** [comment] 2016-05-24 09:25
Here's my webpack config:
const path = require('path');
const merge = require('webpack-merge');
const webpack = require('webpack');
const NpmInstallPlugin = require('npm-install-webpack-plugin');

const TARGET = process.env.npm_lifecycle_event;
const PATHS = {
  app: path.join(__dirname, 'feSRC/'),
  build: path.join(__dirname, 'build/')
};
console.log(PATHS)

process.env.BABEL_ENV = TARGET;

const common = {
  entry: {
    app: [
      // For old browsers
      'eventsource-polyfill',
      'webpack-hot-middleware/client?path=/__webpack_hmr&timeout=20000',
      `${PATHS.app}templates/home/index.js`]
  },
  resolve: {
    extensions: ['', '.js', '.jsx']
  },
  output: {
    path: PATHS.build,
    publicPath: '/build/',
    filename: 'bundle.js'
  },
  module: {
    loaders: [
      {
        test: /\.css$/,
        loaders: ['style', 'css'],
        include: PATHS.app
      },
      {
        test: /\.jsx?$/,
        loaders: ['babel?cacheDirectory'],
        include: PATHS.app
      }
    ]
  }
};

if(TARGET === 'start' || !TARGET) {
  module.exports = merge(common, {
    devtool: 'eval-source-map',
    devServer: {
      contentBase: PATHS.build,

      historyApiFallback: true,
      hot: true,
      inline: true,
      progress: true,

      // display only errors to reduce the amount of output
      stats: 'errors-only',

      // parse host and port from env so this is easy
      // to customize
      host: process.env.HOST || '127.0.0.1',
      port: process.env.PORT || '3600'
    },
    plugins: [
      new webpack.optimize.OccurenceOrderPlugin(),
      new webpack.HotModuleReplacementPlugin(),
      new webpack.NoErrorsPlugin(),
      new NpmInstallPlugin({
        save: true // --save
      })
    ]
  });
}

if(TARGET === 'build') {
  module.exports = merge(common, {});
}

**Comment by antony** [comment] 2016-06-22 07:41
Hi,

I had the same exact error, and the reason is this:

```
module.exports = {
    ...
    output: {
        path: '/src/public/generated',
   },
   ...
}
```

Note the 'path' above.

If you prefix it with a slash, it will work. If you remove the slash, you will get the error you see above.

However, if you prefix it with a slash, it will break production builds as it will try to generate files at the root of your unix/linux device tree (literally `/src`)

Not sure what to do about it. But that's the cause of your error.

**Comment by nhunzaker** [comment] 2016-07-06 17:48
I encountered this issue as well. In my case, I did not have `path` configured within `output`. Adding `path` fixed the issue for me.

**Comment by covertcj** [comment] 2016-08-05 02:11
For what it's worth, I also ran into this problem today, and found a workaround for my scenario.  I was using:

    output: {
        path: './dist',
        filename: 'bundle.js'
    },

but I changed it to use:

    path: __dirname + '/dist',

and everything worked fine afterwards.

**Comment by antony** [comment] 2016-08-05 11:03
This problem has been raised and resolved so many times in this thread. A simple check for absolute paths would go a long way until a proper solution could be put in place.

**Comment by SpaceK33z** [comment] 2016-08-21 19:43
Closing for obvious reasons ;).

**Closed by SpaceK33z** 2016-08-21 19:43 UTC
