### ISSUE TITLE
upgrade the peerDependencies to webpack@2.0 

### ISSUE THREAD

**Issue by vagusX** [webpack/webpack-dev-middleware#45] opened 2015-11-23 04:19 UTC
npm install with following warning:
Peer webpack-dev-middleware@1.2.0 wants webpack@^1.0.0

**Comment by MystK** [comment] 2016-02-16 22:55
I'm also getting something similar to this. Please see the screenshot below.

![image](https://cloud.githubusercontent.com/assets/7399140/13094037/37b22702-d4bd-11e5-9ebb-116ec0ce0aaf.png)

I believe the comparison operator doesn't work because of the "-beta" at the end

**Comment by SpaceK33z** [comment] 2016-09-08 10:15
Do you still have this problem, and if so, what version of npm are you running?

I tried to reproduce this with npm 3.9, but it seems to work (both webpack 1.x and webpack 2.x don't give that message). Also, there is a [semver calculator](https://semver.npmjs.com/), which says that the range `1 || ^2.1.0-beta` is correct.

**Comment by SpaceK33z** [comment] 2016-09-10 08:35
Closing because I know for sure now that this was a bug that has long been fixed.

**Closed by SpaceK33z** 2016-09-10 08:35 UTC
Labels: Needs Response From Author, P1: Urgent
