### ISSUE TITLE
Stats.startTime is offset by watchOffset

### ISSUE THREAD

**Issue by johann-sonntagbauer** [webpack/webpack-dev-middleware#274] opened 2018-03-02 15:45 UTC
* Operating System: Windows 10
* Node Version: 8.6.0
* NPM Version: 5.3.0
* webpack version: 4.1
* webpack-dev-middleware Version: 2.0.6

- [ ] This is a **feature** request
- [X] This is a **bug**

### Code

Start webpack-dev-server in an empty project with a simple index.js entry point.
```
console.log('test');
```

### Expected Behavior
```
(node:8276) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
(node:8276) DeprecationWarning: Tapable.apply is deprecated. Call apply on the plugin directly instead
i ｢wds｣: Project is running at http://localhost:8085/
i ｢wds｣: webpack output is served from /
i ｢wdm｣: Hash: ebb87be9e76118b2f5c3
Version: webpack 4.0.1
Time: 554ms
```
### Actual Behavior
```
(node:8276) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
(node:8276) DeprecationWarning: Tapable.apply is deprecated. Call apply on the plugin directly instead
i ｢wds｣: Project is running at http://localhost:8085/
i ｢wds｣: webpack output is served from /
i ｢wdm｣: Hash: ebb87be9e76118b2f5c3
Version: webpack 4.0.1
Time: 11554ms
```
### For Bugs; How can we reproduce the behavior?
on every build the time is offset by the same amount of time

**Comment by shellscape** [comment] 2018-03-02 15:50
Duplicate of #268. Please search the issues next time around. This is a known issue with webpack v4 and webpack-dev-middleware v2.x. See comments on #268. webpack-dev-middlware v3.0.0 resolves the issue.

**Closed** 2018-03-02 15:50 UTC
Labels: duplicate

**Comment by johann-sonntagbauer** [comment] 2018-03-02 15:54
Sorry I have not found anything for this. Thx for the note I will try to improve. Sorry again.

**Comment by shellscape** [comment] 2018-03-02 15:56
No worries, and no need to apologize 😄 I searched for `watchOffset` in the issues (make sure to remove the filters `is:open` so you get closed issue results too).
