### ISSUE TITLE
problem of latest webpack-dev-server npm packages  in ios9.3

### ISSUE THREAD

**Issue by jiehwa** [webpack/webpack-dev-middleware#222] opened 2017-10-19 04:13 UTC
* Operating System:masOs
* Node Version:v6.9.1
* NPM Version:v3.10.8
* webpack version:v2.5.1
* webpack-dev-middleware Version:v2.9.1

- [x] This is a **bug**

### Code

this is the part of code webpack compiled with the webpack-dev-middleware@2.9.1. As we know the key words `let` and `const` is not support by many browsers and mobile webviews.And it may cause errors when page is loading.In a case ,The page doesn't work in my phone which is ios9.3.  The code compiled with  webpack-dev-middleware@2.7.1 is ok because there are no es6 key words.
```js

// webpack-dev-server module  which is compiled by webpack
/***/ (function(module, exports, __webpack_require__) {

"use strict";
/* WEBPACK VAR INJECTION */(function(__resourceQuery) {

/* global __resourceQuery WorkerGlobalScope self */
/* eslint prefer-destructuring: off */

const url = __webpack_require__(/*! url */ "./node_modules/url/url.js");
const stripAnsi = __webpack_require__(/*! strip-ansi */ "./node_modules/strip-ansi/index.js");
const log = __webpack_require__(/*! loglevel */ "./node_modules/loglevel/lib/loglevel.js").getLogger('webpack-dev-server');
const socket = __webpack_require__(/*! ./socket */ "./node_modules/webpack-dev-server/client/socket.js");
const overlay = __webpack_require__(/*! ./overlay */ "./node_modules/webpack-dev-server/client/overlay.js");
```

```js
// additional code
```

### For Bugs; How can we reproduce the behavior?

npm  install  webpack-dev-middleware@2.9.1 and look up the code compiled by webpack

**Comment by shellscape** [comment] 2017-10-19 04:46
@jiehwa please note that this is the repo for `webpack-dev-middleware` and not `webpack-dev-server`. There is no version webpack-dev-middleware v2.9.1, as the latest version of webpack-dev-middleware is 1.12.0.

Please see this section of the README for webpack-dev-server: https://github.com/webpack/webpack-dev-server#caveats This issue would also be a duplicate of https://github.com/webpack/webpack-dev-server/issues/1143 and https://github.com/webpack/webpack-dev-server/issues/1144.

**Closed by shellscape** 2017-10-19 04:46 UTC
